from typing import Any
from .trace_file import AXIRequestMetadata, SimulationParameters

class SimulationBuilder:
    def __init__(self): ...
    def add_fifo_write(self, safe_offset: int, stage: int, fifo_id: int): ...
    def add_fifo_read(self, safe_offset: int, stage: int, fifo_id: int): ...
    def add_axi_readreq(
        self,
        safe_offset: int,
        stage: int,
        interface_address: int,
        request: AXIRequestMetadata,
    ): ...
    def add_axi_writereq(
        self,
        safe_offset: int,
        stage: int,
        interface_address: int,
        request: AXIRequestMetadata,
    ): ...
    def add_axi_read(self, safe_offset: int, stage: int, interface_address: int): ...
    def add_axi_write(self, safe_offset: int, stage: int, interface_address: int): ...
    def add_axi_writeresp(
        self, safe_offset: int, stage: int, interface_address: int
    ): ...
    def call(
        self,
        safe_offset: int,
        start_stage: int,
        end_stage: int,
        start_delay: int,
        inherit_ap_continue: bool,
    ): ...
    def return_(self, module_name: str, end_stage: int): ...
    def finish(self) -> CompiledSimulation: ...

class CompiledSimulation:
    def execute(self, parameters: SimulationParameters) -> Any: ...
